### ISSUE TITLE
Creating a table in PostgreSQL for storing the suggestions for every residents

### ISSUE THREAD

**Issue by chapwiz** [melvillewong/SSH#11]
One huge SQL table to store each resident's occupancy, where we refuse to create a table for each resident since this does not allow us to apply continuous integration.

#### What does each resident get to see?
- Individual slot (alone at home)
- Common slot (occupancy = 0, nobody is at home)

We shall only have a list of suggestions (timestamp, action etc.) as to how the housework can be distributed. Residents shall take up tasks by communication, not by checkbox within the system.

**Comment by chapwiz** [comment]
I have a new commit to the branch [feature/sql-samples](https://github.com/melvillewong/SSH/tree/feature/sql-samples) where java templates, updated SQL scripts, SQL queries WIP etc. I will further add a file regrading all the changes and implementation.

**Comment by chapwiz** [comment]
A new commit to the branch [feature/sql-samples](https://github.com/melvillewong/SSH/tree/feature/sql-samples) is done.

I have updated the about_sql_queries.md, and completed all the necessary SQL queries for inserting both alone_timestamp and one_resident_timestamp into the table of total_hour_suggestion, with resident_id as one of the keys as well.

This allows us to populate total_hour_suggestion with the appropriate datasets from access_log. Thank you.

**Comment by chapwiz** [comment]
@anson224 Please merge [feature/chore-shifts-duration-recommendation](https://github.com/melvillewong/SSH/tree/feature/chore-shifts-duration-recommendation) on your local machine with the branch [feature/sql-samples (https://github.com/melvillewong/SSH/tree/feature/sql-samples), since there had been a few changes made to about_sql_queries.md aka proposed_queries.md within [feature/chore-shifts-duration-recommendation](https://github.com/melvillewong/SSH/tree/feature/chore-shifts-duration-recommendation). Thank you.

**Comment by anson224** [comment]
> @anson224 Please merge [feature/chore-shifts-duration-recommendation](https://github.com/melvillewong/SSH/tree/feature/chore-shifts-duration-recommendation) on your local machine with the branch [feature/sql-samples](https://github.com/melvillewong/SSH/tree/feature/sql-samples), since there had been a few changes made to about_sql_queries.md aka proposed_queries.md within [feature/chore-shifts-duration-recommendation](https://github.com/melvillewong/SSH/tree/feature/chore-shifts-duration-recommendation). Thank you.

Sure thing! Will do
