### ISSUE TITLE
Implementation of Gradle

### ISSUE THREAD

**Issue by chapwiz** [melvillewong/SSH#12]
We shall enhance the robustness of the program by implementing Gradle.

**Comment by melvillewong** [comment]
I pushed a branch named feature/gradle-implementation to remote, feel free to take a look.
Inside the gradle, I have implemented a sample server-client-service application.
Instructions are written in about_gradle.md

We will take gradle implementation as a future development.

**Comment by chapwiz** [comment]
We shall only require a single test base for the client only, since the Server.java (File name unfinalised) would only be used to initialise the PostgreSQL server and only listens to user inputs which then would respond accordingly, the output is sent straight to the Client.java (File name unfinalised).

With that being said, we shall only focus on the tests for Client.java, tests for Server.java is not required.

Nevertheless thank you for the effort, we will list this as a future development.

**Comment by melvillewong** [comment]
1. I've implemented Docker's plugin in Gradle to access PostgreSQL Container.

2. In addition, I've added commented JDBC driver as dependency for later use if it's needed.

(More are shown in about_gradle.md in this branch)

**Comment by melvillewong** [comment]
I just pushed the feature branch to the remote. Here’s what I've done:

1. Implemented the main Java scripts (Server, Client, Service) using Gradle.
2. Updated the about_gradle.md file to explain how the application works.

> (@chapwiz, I've changed the names of those classes for convenience. Let me know if you prefer to change them back.)"
